export type Interview = {
  id: number;
  title: string;
  subtitle: string;
  date: Date;
  photographer: string[];
  interviewer: string[];
  interviewee: string[];
  content: Paragraph[];
};

export type Paragraph = {
  speaker?: string;
  text?: string | undefined;
  imagePath?: string | undefined;
};

export const interviews: Interview[] = [
  {
    id: 1,
    title: "첫인상은 '아, 이거다!' 였어요",
    subtitle: "doby의 이야기",
    date: new Date("2021-03-21"),
    interviewer: ["byukim"],
    interviewee: ["doby"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 2,
    title: "기록하고 정리하는 걸 좋아해요",
    subtitle: "mki의 이야기",
    date: new Date("2021-03-21"),
    interviewer: ["yechoi"],
    interviewee: ["mki"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 3,
    title: "특이한 스타일을 하면 일상에 재밌는 일이 많이 생겨요",
    subtitle: "kyukim의 이야기",
    date: new Date("2021-03-21"),
    interviewer: ["yechoi"],
    interviewee: ["kyukim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 4,
    title: "기뻐할 겨를 없이 세그폴트를 잡고 있었어요",
    subtitle: "hseo의 이야기",
    date: new Date("2021-03-30"),
    interviewer: ["byukim"],
    interviewee: ["hseo"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 5,
    title: "42서울에서의 삶은 '어른스럽다'에 가까운 것 같아요",
    subtitle: "soooh, inyang의 이야기",
    date: new Date("2021-04-06"),
    interviewer: ["yechoi"],
    interviewee: ["soooh", "inyang"],
    photographer: ["jwon", "yeslee"],
    content: [],
  },
  {
    id: 6,
    title: "달리는 삶을 살고 싶어요, 늘 그랬듯이",
    subtitle: "ryukim의 이야기",
    date: new Date("2021-04-13"),
    interviewer: ["iwoo"],
    interviewee: ["ryukim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 7,
    title: "만약 누가 라 피신을 다시 하라고 묻는다면…",
    subtitle: "mseo, seohchoi의 이야기",
    date: new Date("2021-04-20"),
    interviewer: ["byukim"],
    interviewee: ["mseo", "seohchoi"],
    photographer: ["jwon", "yeslee"],
    content: [],
  },
  {
    id: 8,
    title: "스스로 벽을 넘는 능력을 갖췄으면 좋겠어요",
    subtitle: "amin의 이야기",
    date: new Date("2021-04-22"),
    interviewer: ["yechoi"],
    interviewee: ["amin"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 9,
    title: "하고 싶은 일이 생기면 무조건 일을 벌이는 편이에요",
    subtitle: "sunpark의 이야기",
    date: new Date("2021-04-27"),
    interviewer: ["iwoo"],
    interviewee: ["sunpark"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 10,
    title: "꼭 붙었으면 좋겠어요",
    subtitle: "jseol의 이야기",
    date: new Date("2021-05-04"),
    interviewer: ["yechoi"],
    interviewee: ["jseol"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 11,
    title: "내 입지를 내가 직접 없애고 있다는 생각이 들었어요",
    subtitle: "jekim의 이야기",
    date: new Date("2021-05-11"),
    interviewer: ["byukim"],
    interviewee: ["jekim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 12,
    title: "합류한 건 교육 혁신에 대한 꿈 때문이에요",
    subtitle: "STARK의 이야기",
    date: new Date("2021-05-18"),
    interviewer: ["yechoi"],
    interviewee: ["STARK"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 13,
    title: "시큐어 코딩을 할 줄 아는 개발자가 되고 싶어요",
    subtitle: "jaeskim의 이야기",
    date: new Date("2021-05-25"),
    interviewer: ["yechoi"],
    interviewee: ["jaeskim"],
    photographer: ["jaewpark", "jwon"],
    content: [],
  },
  {
    id: 14,
    title: "인생은 한 번 뿐이니까 YOLO 정신으로 지원했죠",
    subtitle: "hyeonski의 이야기",
    date: new Date("2021-06-01"),
    interviewer: ["byukim"],
    interviewee: ["hyeonski"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 15,
    title: "저는 뭔가에 잘 꽂혀요",
    subtitle: "hyeyoo의 이야기",
    date: new Date("2021-06-08"),
    interviewer: ["yeonwlee", "myungkim"],
    interviewee: ["hyeyoo"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 16,
    title: "마지막까지 하고 싶은 걸 하면서 살고 싶어요",
    subtitle: "gshim의 이야기",
    date: new Date("2021-06-15"),
    interviewer: ["hmoon"],
    interviewee: ["gshim"],
    photographer: ["jaewpark", "hmoon"],
    content: [],
  },
  {
    id: 17,
    title: "‘개발을 배우는 과정에서의 행복’이 중요한 가치라는 생각이 들어요",
    subtitle: "eunhkim의 이야기",
    date: new Date("2021-06-22"),
    interviewer: ["yechoi", "yeonwlee", "myungkim"],
    interviewee: ["eunhkim"],
    photographer: ["jwon", "jaewpark"],
    content: [],
  },
  {
    id: 18,
    title: "내가 좋아하는 일을 하면서 돈을 벌고 싶다고 생각했어요",
    subtitle: "hyekim의 이야기",
    date: new Date("2021-06-29"),
    interviewer: ["byukim"],
    interviewee: ["hyekim"],
    photographer: ["jaewpark"],
    content: [],
  },
  {
    id: 19,
    title: "새로운 교육 시스템을 만드는 건 매우 중요하고 의미 있는 일이잖아요",
    subtitle: "Dall의 이야기",
    date: new Date("2021-07-02"),
    interviewer: ["byukim", "yechoi", "jwon"],
    interviewee: ["Dall"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 20,
    title:
      "프로와 아마추어의 차이는 '자신을 평가할 줄 아는 능력'의 유무에 있어요",
    subtitle: "Dall의 이야기",
    date: new Date("2021-07-06"),
    interviewer: ["byukim", "yechoi", "jwon"],
    interviewee: ["Dall"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 21,
    title:
      "‘한밤의 늑대인간’을 실제 사용할 수 있는 어플리케이션으로 만들어보고 싶어요",
    subtitle: "kalee의 이야기",
    date: new Date("2021-07-13"),
    interviewer: ["myungkim"],
    interviewee: ["kalee"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 22,
    title: "이렇게 행복하다고 느끼는 것 자체도 행복해요",
    subtitle: "sohan의 이야기",
    date: new Date("2021-07-20"),
    interviewer: ["yechoi"],
    interviewee: ["sohan"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 23,
    title: "제 동력원은 사람이에요",
    subtitle: "yomoon의 이야기",
    date: new Date(""),
    interviewer: [],
    interviewee: [],
    photographer: [""],
    content: [],
  },
  {
    id: 24,
    title: '"그림과 프로그래밍 두 마리 토끼를 모두 잡으려고 노력하고 있어요"',
    subtitle: "hnoh의 이야기",
    date: new Date("2021-08-03"),
    interviewer: ["byukim"],
    interviewee: ["hnoh"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 25,
    title: "이런 장점을 타고난 게 운이 좋았다고 생각해요",
    subtitle: "myoon의 이야기",
    date: new Date("2021-09-14"),
    interviewer: ["yechoi"],
    interviewee: ["myoon"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 26,
    title: "The Hitchhikers - 1",
    subtitle: "yuchung, kyunpark, jrhee의 이야기",
    date: new Date("2021-09-28"),
    interviewer: ["soooh", "yeonwlee", "yechoi"],
    interviewee: ["yuchung", "kyunpark", "jrhee"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 27,
    title: "The Hitchhikers - 2",
    subtitle: "apark, hrha, cjeon의 이야기",
    date: new Date("2021-10-05"),
    interviewer: ["byukim", "seungyel", "hmoon"],
    interviewee: ["apark", "hrha", "cjeon"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 28,
    title: "어느 날 문득 멘토링을 해야겠다는 생각이 들었어요",
    subtitle: "m-jongfeel-kim의 이야기",
    date: new Date("2021-11-04"),
    interviewer: ["seungyel"],
    interviewee: ["m-jongfeel-kim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 29,
    title: "새로운 사람을 두려워하지 않아요",
    subtitle: "echung의 이야기",
    date: new Date("2021-12-07"),
    interviewer: ["hojo"],
    interviewee: ["echung"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 30,
    title: "42Seoul에 창업하러 왔습니다",
    subtitle: "kilee의 이야기",
    date: new Date("2021-12-20"),
    interviewer: ["hojo"],
    interviewee: ["kilee"],
    photographer: ["hmoon", "jaewpark"],
    content: [],
  },
  {
    id: 31,
    title: "클러스터에 다시 나오니까 너무 재미있어요",
    subtitle: "seungoh의 이야기",
    date: new Date("2022-01-13"),
    interviewer: ["hojo", "echung"],
    interviewee: ["seungoh"],
    photographer: ["hmoon"],
    content: [],
  },
  {
    id: 32,
    title: "저는 제가 하고 싶은 거 하면서 살고 싶어요",
    subtitle: "jolim의 이야기",
    date: new Date("2022-01-26"),
    interviewer: ["soooh"],
    interviewee: ["jolim"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 33,
    title: "나이는 중요하지 않은 거 같아요, 적어도 이곳에서는",
    subtitle: "hyenam의 이야기",
    date: new Date("2022-02-04"),
    interviewer: ["hojo"],
    interviewee: ["hyenam"],
    photographer: ["hmoon", "jwon"],
    content: [],
  },
  {
    id: 34,
    title: "'만들고 싶다'가 가장 중요해요",
    subtitle: "m-youknowone의 이야기",
    date: new Date("2022-02-11"),
    interviewer: ["echung", "haryu"],
    interviewee: ["m-youknowone"],
    photographer: ["hmoon"],
    content: [],
  },
  {
    id: 35,
    title: "42서울 사람들과 헤어지고 싶지 않은 마음이 커요",
    subtitle: "sehyan의 이야기",
    date: new Date("2022-02-18"),
    interviewer: ["jaekim", "byukim"],
    interviewee: ["sehyan"],
    photographer: ["jaewpark"],
    content: [],
  },
  {
    id: 36,
    title: "나를 믿는 믿음",
    subtitle: "bomoon의 이야기",
    date: new Date("2022-03-11"),
    interviewer: ["haryu"],
    interviewee: ["bomoon"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 37,
    title: "42Seoul 커뮤니티에 도움이 되고 싶었어요.",
    subtitle: "jseo의 이야기",
    date: new Date("2022-04-01"),
    interviewer: ["hojo"],
    interviewee: ["jseo"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 39,
    title: "중요한 건 일을 해나갈 수 있는 명분이에요",
    subtitle: "gulee의 이야기",
    date: new Date("2022-05-02"),
    interviewer: ["ljeongin", "suekang"],
    interviewee: ["gulee"],
    photographer: ["hdoo"],
    content: [],
  },
  {
    id: 40,
    title: "도전할 자신감은 도전에서 나온다",
    subtitle: "donghyuk, nheo의 이야기",
    date: new Date("2022-05-06"),
    interviewer: ["haryu"],
    interviewee: ["donghyuk", "nheo"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 41,
    title: "협력, 소통을 배우는 시간",
    subtitle: "jihyukim, jabae의 이야기",
    date: new Date("2022-06-03"),
    interviewer: ["haryu"],
    interviewee: ["jihyukim", "jabae"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 42,
    title: "사람들이 다 치유해준 것 같아요",
    subtitle: "jiychoi, junmkang의 이야기",
    date: new Date("2022-07-19"),
    interviewer: ["hmoon", "jaewpark"],
    interviewee: ["jiychoi", "junmkang"],
    photographer: ["jaewpark"],
    content: [],
  },
  {
    id: 43,
    title: "Life is 42",
    subtitle: "kristine의 이야기",
    date: new Date("2022-09-13"),
    interviewer: ["yechoi"],
    interviewee: ["kristine"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 44,
    title: "yego에서 yeogo, 그리고 yeongo로",
    subtitle: "yeongo의 이야기",
    date: new Date("2022-10-25"),
    interviewer: ["changhle", "jerhee"],
    interviewee: ["yeongo"],
    photographer: ["hdoo"],
    content: [],
  },
];
