export type Interview = {
  id: number;
  title: string;
  subtitle: string;
  date: Date;
  photographer: string[];
  interviewer: string[];
  interviewee: string[];
  content: Paragraph[];
};

export type Paragraph = {
  text?: string | undefined;
  imagePath?: string | undefined;
};

const interviews: Interview[] = [
  {
    id: 1,
    title: "첫인상은 '아, 이거다!' 였어요",
    subtitle: "doby의 이야기",
    date: new Date("2021-03-21"),
    photographer: ["jwon"],
    interviewer: ["byukim"],
    interviewee: ["doby"],
    content: [],
  },
  {
    id: 2,
    title: "기록하고 정리하는 걸 좋아해요",
    subtitle: "mki의 이야기",
    date: new Date("2021-03-21"),
    photographer: ["jwon"],
    interviewer: ["yechoi"],
    interviewee: ["mki"],
    content: [],
  },
  {
    id: 3,
    title: "특이한 스타일을 하면 일상에 재밌는 일이 많이 생겨요",
    subtitle: "kyukim의 이야기",
    date: new Date("2021-03-21"),
    photographer: ["jwon"],
    interviewer: ["yechoi"],
    interviewee: ["kyukim"],
    content: [],
  },
  {
    id: 4,
    title: "기뻐할 겨를 없이 세그폴트를 잡고 있었어요",
    subtitle: "hseo의 이야기",
    date: new Date("2021-03-30"),
    photographer: ["jwon"],
    interviewer: ["byukim"],
    interviewee: ["hseo"],
    content: [],
  },
  {
    id: 5,
    title: "42서울에서의 삶은 '어른스럽다'에 가까운 것 같아요",
    subtitle: "soooh, inyang의 이야기",
    date: new Date("2021-04-06"),
    photographer: ["jwon", "yeslee"],
    interviewer: ["yechoi"],
    interviewee: ["soooh", "inyang"],
    content: [],
  },
  {
    id: 6,
    title: "달리는 삶을 살고 싶어요, 늘 그랬듯이",
    subtitle: "ryukim의 이야기",
    date: new Date("2021-04-13"),
    photographer: ["jwon"],
    interviewer: ["iwoo"],
    interviewee: ["ryukim"],
    content: [],
  },
  {
    id: 7,
    title: "만약 누가 라 피신을 다시 하라고 묻는다면…",
    subtitle: "mseo, seohchoi의 이야기",
    date: new Date("2021-04-20"),
    photographer: ["jwon", "yeslee"],
    interviewer: ["byukim"],
    interviewee: ["mseo", "seohchoi"],
    content: [],
  },
  {
    id: 8,
    title: "스스로 벽을 넘는 능력을 갖췄으면 좋겠어요",
    subtitle: "amin의 이야기",
    date: new Date("2021-04-22"),
    photographer: ["jwon"],
    interviewer: ["yechoi"],
    interviewee: ["amin"],
    content: [],
  },
  {
    id: 9,
    title: "하고 싶은 일이 생기면 무조건 일을 벌이는 편이에요",
    subtitle: "sunpark의 이야기",
    date: new Date("2021-04-27"),
    photographer: ["yeslee"],
    interviewer: ["iwoo"],
    interviewee: ["sunpark"],
    content: [],
  },
  {
    id: 10,
    title: "꼭 붙었으면 좋겠어요",
    subtitle: "jseol의 이야기",
    date: new Date("2021-05-04"),
    photographer: ["jwon"],
    interviewer: ["yechoi"],
    interviewee: ["jseol"],
    content: [],
  },
  {
    id: 11,
    title: "내 입지를 내가 직접 없애고 있다는 생각이 들었어요",
    subtitle: "jekim의 이야기",
    date: new Date("2021-05-11"),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
  {
    id: 11,
    title: "",
    subtitle: "",
    date: new Date(""),
    photographer: [""],
    interviewer: [""],
    interviewee: [""],
    content: [],
  },
];
