export type Interview = {
  id: number;
  title: string;
  subtitle: string;
  date: Date;
  photographer: string[];
  interviewer: string[];
  interviewee: string[];
  content: Paragraph[];
};

export type Paragraph = {
  speaker?: string;
  text?: string | undefined;
  imagePath?: string | undefined;
};

export const interviews: Interview[] = [
  {
    id: 1,
    title: "첫인상은 '아, 이거다!' 였어요",
    subtitle: "doby의 이야기",
    date: new Date("2021-03-21"),
    interviewer: ["byukim"],
    interviewee: ["doby"],
    photographer: ["jwon"],
    content: [
      {
        text: "42를 처음 알게 되었을 때 첫인상은 '아, 이거다! ' 였어요. 기존 교육기관의 방식은 고정된 커리큘럼을 따라가는 식이어서 마음에 안 들었지만, 42는 달랐거든요. 나의 속도에 맞춰서 커리큘럼을 진행할 수 있고, 활성화된 커뮤니티도 존재하는 곳이었기 때문에 이곳은 나를 위한 곳이라고 생각했죠. 그리고 '프랑스어도 모르고, 코딩도 모르는데 지원해도 될까요?' 란 질문에 42가 '바로 그런 사람을 우리가 원하는 겁니다' 라고 답했다고 전해 들어서, 여기가 더 매력적이라고 느꼈어요.",
      },
      {
        text: "블랙홀에 관해 얘기하자면, 예전에는 블랙홀이라는 제도가 아예 없었어요. 누구든지 본인의 속도에 맞춰서 학습을 진행할 수 있었죠. 그런데 학생 비자를 받기 위해 42에 등록만 하고 실제로는 학습을 진행하지 않는 사람들이 생겨나면서, 이들을 제외하자는 의도로 블랙홀을 만들었다고 하더라고요. 학습이 느린 사람을 제외하는 의도가 아니기 때문에, 이너 서클을 돌파하면 블랙홀은 사라지는 것을 알 수 있죠. 그때부터는 영원한 42인이 되는 거고요(웃음). 아 물론 현재 과정은 다를 수도 있어요! 현재는 예전보다 블랙홀도 빡빡하고 과제들도 새로운 거로 대체돼서 어떨지는 잘 모르겠네요.",
      },
      {
        text: "42서울은 프랑스에 있을 때 이민석 학장님의 연락을 통해 알게 되었어요. 42를 서울에 만들 예정인데, 인턴으로 들어오라는 제안이었어요. 제가 42를 너무 좋아하기도 했고, 42서울이 생겼으면 좋겠다고 생각하고 있어서 jai와 함께 지원하게 되었죠. 사실 인턴 제의가 들어오기 전에도, 한국에서 몇몇 분들이 파리 캠퍼스를 찾아오셨어요. 그때 저희를 인터뷰하시면서 42서울이 생기면 어떨지 여쭤보셨는데, 대다수의 의견은 부정적이었답니다. 나이에 따른 서열 등 한국적인 문화 때문에 42가 성공하기 어렵다고 생각했거든요. 하지만! 그때 저는 긍정적인 의견을 표출하면서 42서울 유치에 조금이나마 기여를 했답니다(웃음).",
      },
      {
        text: "42서울에 있으면서 여러 행사에 참여했었는데, 그 이유는 공동체 의식 때문이에요. 파리 캠퍼스에서도 크리스마스 같은 특별한 날에는 이벤트를 많이 하거든요! 그런 이벤트를 통해 즐거운 순간들이 많이 쌓이다 보면, 카뎃 분들이 커뮤니티에 애정을 가지게 되고 그럼 나중에 과정을 마친 카뎃 분들이 돌아와 커뮤니티에 기여를 하는 선순환이 생길 것이라 기대했어요. 그래서 모두가 함께 즐거운 시간을 보낼 수 있는 이벤트들을 많이 기획하고 참여했답니다.",
      },
      {
        text: "1기 1차 피신이 끝났을 때, 피신 슬랙에 긴 글을 남긴 적이 있어요. 그 글은 피신 Final Exam 도중에 쓰게 된 글인데요. 왜 쓰게 되었냐면… 피신은 제 인생에서 잊을 수 없는 기억이에요. 42서울의 피시너 분들에게도 잊을 수 없는 기억일 거구요. 그리고 해외 캠퍼스와는 다르게 42서울은 피신을 재도전할 수 없으니까 누군가와는 작별해야 하는데 그런 아쉬움도 있고, 저를 많이 좋아해 주신 분들에 대한 고마움도 있고… 아무튼 제가 피신 때 느꼈던 감정을 느끼고 있을 피시너 분들에게 '여러분은 대단한 사람들이에요’란 메시지를 전해주고 싶었어요. 여러 복합적인 감정들이 느껴져서 그 글을 쓰게 되었네요(웃음).",
      },
      {
        text: "인턴을 하면서 기억나는 순간들이 정말 많지만, 2020년 2월 피신을 한번 말씀드리고 싶어요. 맨 처음 피신은 처음이자 마지막으로 마스크 없이 자유롭게 평가하던 시기였고 또 모든 사람이 클러스터에서 밤새우면서 고생하던 시기였고… 기억나는 것을 몇 가지 얘기해보자면, 피신 슬랙에 other_twitter란 채널이 있었어요. 그 채널을 처음 염탐할 때 딱 1분 계셨는데, 나중에 보니까 트위터 감성이 가득한 글들을 쭉 올리시더라고요! 알고 보니 피신은 보안 때문에 정보를 유출할 수 없으니 대신 그 채널에 글을 올리시는 거였어요(웃음). 시간이 지나니까 그 채널이 유명해져서, 마지막 날 하루 전에는 팬 미팅을 가지기도 했답니다!",
      },
      {
        text: "피신을 시작하시는 분들에게 말씀을 드리자면 우선 42라는 커뮤니티가 기존의 학교 같은 공간과는 매우 달라요. 스스로 개척해나가야 하고, 주변인들과 계속 소통해야 하고, 그러면서도 유머러스한 면을 요구하기도 하고. '저렇게까지 통통 튀면 튀어 나가지 않을까?' 하는 사람도 있고 말이죠. 한국 내의 작은 외국이라고 생각하고, 어떤 일이라도 일어날 수 있다는 오픈 마인드를 가지고 들어오면 더 즐길 수 있을 거예요.",
      },
    ],
  },
  {
    id: 2,
    title: "기록하고 정리하는 걸 좋아해요",
    subtitle: "mki의 이야기",
    date: new Date("2021-03-21"),
    interviewer: ["yechoi"],
    interviewee: ["mki"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 3,
    title: "특이한 스타일을 하면 일상에 재밌는 일이 많이 생겨요",
    subtitle: "kyukim의 이야기",
    date: new Date("2021-03-21"),
    interviewer: ["yechoi"],
    interviewee: ["kyukim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 4,
    title: "기뻐할 겨를 없이 세그폴트를 잡고 있었어요",
    subtitle: "hseo의 이야기",
    date: new Date("2021-03-30"),
    interviewer: ["byukim"],
    interviewee: ["hseo"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 5,
    title: "42서울에서의 삶은 '어른스럽다'에 가까운 것 같아요",
    subtitle: "soooh, inyang의 이야기",
    date: new Date("2021-04-06"),
    interviewer: ["yechoi"],
    interviewee: ["soooh", "inyang"],
    photographer: ["jwon", "yeslee"],
    content: [],
  },
  {
    id: 6,
    title: "달리는 삶을 살고 싶어요, 늘 그랬듯이",
    subtitle: "ryukim의 이야기",
    date: new Date("2021-04-13"),
    interviewer: ["iwoo"],
    interviewee: ["ryukim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 7,
    title: "만약 누가 라 피신을 다시 하라고 묻는다면…",
    subtitle: "mseo, seohchoi의 이야기",
    date: new Date("2021-04-20"),
    interviewer: ["byukim"],
    interviewee: ["mseo", "seohchoi"],
    photographer: ["jwon", "yeslee"],
    content: [],
  },
  {
    id: 8,
    title: "스스로 벽을 넘는 능력을 갖췄으면 좋겠어요",
    subtitle: "amin의 이야기",
    date: new Date("2021-04-22"),
    interviewer: ["yechoi"],
    interviewee: ["amin"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 9,
    title: "하고 싶은 일이 생기면 무조건 일을 벌이는 편이에요",
    subtitle: "sunpark의 이야기",
    date: new Date("2021-04-27"),
    interviewer: ["iwoo"],
    interviewee: ["sunpark"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 10,
    title: "꼭 붙었으면 좋겠어요",
    subtitle: "jseol의 이야기",
    date: new Date("2021-05-04"),
    interviewer: ["yechoi"],
    interviewee: ["jseol"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 11,
    title: "내 입지를 내가 직접 없애고 있다는 생각이 들었어요",
    subtitle: "jekim의 이야기",
    date: new Date("2021-05-11"),
    interviewer: ["byukim"],
    interviewee: ["jekim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 12,
    title: "합류한 건 교육 혁신에 대한 꿈 때문이에요",
    subtitle: "STARK의 이야기",
    date: new Date("2021-05-18"),
    interviewer: ["yechoi"],
    interviewee: ["STARK"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 13,
    title: "시큐어 코딩을 할 줄 아는 개발자가 되고 싶어요",
    subtitle: "jaeskim의 이야기",
    date: new Date("2021-05-25"),
    interviewer: ["yechoi"],
    interviewee: ["jaeskim"],
    photographer: ["jaewpark", "jwon"],
    content: [],
  },
  {
    id: 14,
    title: "인생은 한 번 뿐이니까 YOLO 정신으로 지원했죠",
    subtitle: "hyeonski의 이야기",
    date: new Date("2021-06-01"),
    interviewer: ["byukim"],
    interviewee: ["hyeonski"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 15,
    title: "저는 뭔가에 잘 꽂혀요",
    subtitle: "hyeyoo의 이야기",
    date: new Date("2021-06-08"),
    interviewer: ["yeonwlee", "myungkim"],
    interviewee: ["hyeyoo"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 16,
    title: "마지막까지 하고 싶은 걸 하면서 살고 싶어요",
    subtitle: "gshim의 이야기",
    date: new Date("2021-06-15"),
    interviewer: ["hmoon"],
    interviewee: ["gshim"],
    photographer: ["jaewpark", "hmoon"],
    content: [],
  },
  {
    id: 17,
    title: "‘개발을 배우는 과정에서의 행복’이 중요한 가치라는 생각이 들어요",
    subtitle: "eunhkim의 이야기",
    date: new Date("2021-06-22"),
    interviewer: ["yechoi", "yeonwlee", "myungkim"],
    interviewee: ["eunhkim"],
    photographer: ["jwon", "jaewpark"],
    content: [],
  },
  {
    id: 18,
    title: "내가 좋아하는 일을 하면서 돈을 벌고 싶다고 생각했어요",
    subtitle: "hyekim의 이야기",
    date: new Date("2021-06-29"),
    interviewer: ["byukim"],
    interviewee: ["hyekim"],
    photographer: ["jaewpark"],
    content: [],
  },
  {
    id: 19,
    title: "새로운 교육 시스템을 만드는 건 매우 중요하고 의미 있는 일이잖아요",
    subtitle: "Dall의 이야기",
    date: new Date("2021-07-02"),
    interviewer: ["byukim", "yechoi", "jwon"],
    interviewee: ["Dall"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 20,
    title:
      "프로와 아마추어의 차이는 '자신을 평가할 줄 아는 능력'의 유무에 있어요",
    subtitle: "Dall의 이야기",
    date: new Date("2021-07-06"),
    interviewer: ["byukim", "yechoi", "jwon"],
    interviewee: ["Dall"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 21,
    title:
      "‘한밤의 늑대인간’을 실제 사용할 수 있는 어플리케이션으로 만들어보고 싶어요",
    subtitle: "kalee의 이야기",
    date: new Date("2021-07-13"),
    interviewer: ["myungkim"],
    interviewee: ["kalee"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 22,
    title: "이렇게 행복하다고 느끼는 것 자체도 행복해요",
    subtitle: "sohan의 이야기",
    date: new Date("2021-07-20"),
    interviewer: ["yechoi"],
    interviewee: ["sohan"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 23,
    title: "제 동력원은 사람이에요",
    subtitle: "yomoon의 이야기",
    date: new Date(""),
    interviewer: [],
    interviewee: [],
    photographer: [""],
    content: [],
  },
  {
    id: 24,
    title: '"그림과 프로그래밍 두 마리 토끼를 모두 잡으려고 노력하고 있어요"',
    subtitle: "hnoh의 이야기",
    date: new Date("2021-08-03"),
    interviewer: ["byukim"],
    interviewee: ["hnoh"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 25,
    title: "이런 장점을 타고난 게 운이 좋았다고 생각해요",
    subtitle: "myoon의 이야기",
    date: new Date("2021-09-14"),
    interviewer: ["yechoi"],
    interviewee: ["myoon"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 26,
    title: "The Hitchhikers - 1",
    subtitle: "yuchung, kyunpark, jrhee의 이야기",
    date: new Date("2021-09-28"),
    interviewer: ["soooh", "yeonwlee", "yechoi"],
    interviewee: ["yuchung", "kyunpark", "jrhee"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 27,
    title: "The Hitchhikers - 2",
    subtitle: "apark, hrha, cjeon의 이야기",
    date: new Date("2021-10-05"),
    interviewer: ["byukim", "seungyel", "hmoon"],
    interviewee: ["apark", "hrha", "cjeon"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 28,
    title: "어느 날 문득 멘토링을 해야겠다는 생각이 들었어요",
    subtitle: "m-jongfeel-kim의 이야기",
    date: new Date("2021-11-04"),
    interviewer: ["seungyel"],
    interviewee: ["m-jongfeel-kim"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 29,
    title: "새로운 사람을 두려워하지 않아요",
    subtitle: "echung의 이야기",
    date: new Date("2021-12-07"),
    interviewer: ["hojo"],
    interviewee: ["echung"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 30,
    title: "42Seoul에 창업하러 왔습니다",
    subtitle: "kilee의 이야기",
    date: new Date("2021-12-20"),
    interviewer: ["hojo"],
    interviewee: ["kilee"],
    photographer: ["hmoon", "jaewpark"],
    content: [],
  },
  {
    id: 31,
    title: "클러스터에 다시 나오니까 너무 재미있어요",
    subtitle: "seungoh의 이야기",
    date: new Date("2022-01-13"),
    interviewer: ["hojo", "echung"],
    interviewee: ["seungoh"],
    photographer: ["hmoon"],
    content: [],
  },
  {
    id: 32,
    title: "저는 제가 하고 싶은 거 하면서 살고 싶어요",
    subtitle: "jolim의 이야기",
    date: new Date("2022-01-26"),
    interviewer: ["soooh"],
    interviewee: ["jolim"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 33,
    title: "나이는 중요하지 않은 거 같아요, 적어도 이곳에서는",
    subtitle: "hyenam의 이야기",
    date: new Date("2022-02-04"),
    interviewer: ["hojo"],
    interviewee: ["hyenam"],
    photographer: ["hmoon", "jwon"],
    content: [],
  },
  {
    id: 34,
    title: "'만들고 싶다'가 가장 중요해요",
    subtitle: "m-youknowone의 이야기",
    date: new Date("2022-02-11"),
    interviewer: ["echung", "haryu"],
    interviewee: ["m-youknowone"],
    photographer: ["hmoon"],
    content: [],
  },
  {
    id: 35,
    title: "42서울 사람들과 헤어지고 싶지 않은 마음이 커요",
    subtitle: "sehyan의 이야기",
    date: new Date("2022-02-18"),
    interviewer: ["jaekim", "byukim"],
    interviewee: ["sehyan"],
    photographer: ["jaewpark"],
    content: [],
  },
  {
    id: 36,
    title: "나를 믿는 믿음",
    subtitle: "bomoon의 이야기",
    date: new Date("2022-03-11"),
    interviewer: ["haryu"],
    interviewee: ["bomoon"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 37,
    title: "42Seoul 커뮤니티에 도움이 되고 싶었어요.",
    subtitle: "jseo의 이야기",
    date: new Date("2022-04-01"),
    interviewer: ["hojo"],
    interviewee: ["jseo"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 39,
    title: "중요한 건 일을 해나갈 수 있는 명분이에요",
    subtitle: "gulee의 이야기",
    date: new Date("2022-05-02"),
    interviewer: ["ljeongin", "suekang"],
    interviewee: ["gulee"],
    photographer: ["hdoo"],
    content: [],
  },
  {
    id: 40,
    title: "도전할 자신감은 도전에서 나온다",
    subtitle: "donghyuk, nheo의 이야기",
    date: new Date("2022-05-06"),
    interviewer: ["haryu"],
    interviewee: ["donghyuk", "nheo"],
    photographer: ["yeslee"],
    content: [],
  },
  {
    id: 41,
    title: "협력, 소통을 배우는 시간",
    subtitle: "jihyukim, jabae의 이야기",
    date: new Date("2022-06-03"),
    interviewer: ["haryu"],
    interviewee: ["jihyukim", "jabae"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 42,
    title: "사람들이 다 치유해준 것 같아요",
    subtitle: "jiychoi, junmkang의 이야기",
    date: new Date("2022-07-19"),
    interviewer: ["hmoon", "jaewpark"],
    interviewee: ["jiychoi", "junmkang"],
    photographer: ["jaewpark"],
    content: [],
  },
  {
    id: 43,
    title: "Life is 42",
    subtitle: "kristine의 이야기",
    date: new Date("2022-09-13"),
    interviewer: ["yechoi"],
    interviewee: ["kristine"],
    photographer: ["jwon"],
    content: [],
  },
  {
    id: 44,
    title: "yego에서 yeogo, 그리고 yeongo로",
    subtitle: "yeongo의 이야기",
    date: new Date("2022-10-25"),
    interviewer: ["changhle", "jerhee"],
    interviewee: ["yeongo"],
    photographer: ["hdoo"],
    content: [],
  },
];
